version: '3.8'

services:
    composer:
        image: composer:latest
        environment:
            COMPOSER_CACHE_DIR: /app/.cache/composer
        volumes:
            - ./:/app
        working_dir: /app

    phpunit:
        image: php:8.1-cli
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: vendor/bin/phpunit
