name: PHPUnit

on:
    - push

jobs:
    test:
        strategy:
            matrix:
                image:
                    - 'php:7.4-cli-alpine'
                    - 'php:8.0-cli-alpine'
                    - 'php:8.1-cli-alpine'
                    - 'php:8.2-cli-alpine'

                dependencies:
                    - 'illuminate/database:^8.0'
                    - 'illuminate/database:^9.0'
                    - 'illuminate/database:^10.0'

                prefer_lowest: [0, 1]

                exclude:
                    - image: 'php:7.4-cli-alpine'
                      dependencies: 'illuminate/database:^10.0'

                    - image: 'php:7.4-cli-alpine'
                      dependencies: 'illuminate/database:^9.0'

                    - image: 'php:8.0-cli-alpine'
                      dependencies: 'illuminate/database:^10.0'

        runs-on: ubuntu-latest
        container:
            image: ${{ matrix.image }}
            env:
                COMPOSER_PREFER_STABLE: 1
                COMPOSER_PREFER_LOWEST: ${{ matrix.prefer_lowest }}


        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Composer
              run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

            - name: Specify Composer dependencies
              run: composer require ${{ matrix.dependencies }} --no-update --no-interaction --no-progress

            - name: Update Composer dependencies
              run: composer update --no-interaction --no-progress

            - name: Run PHPUnit
              run: vendor/bin/phpunit
