name: PHPUnit

on:
    - push

jobs:
    test:
        strategy:
            matrix:
                platform:
                    - {image: 'php:8.0-cli-alpine', php: 8.0.2}
                prefer_lowest:
                    - 1
                    - 0

        runs-on: ubuntu-latest
        container:
            image: ${{ matrix.platform.image }}
            env:
                COMPOSER_PREFER_LOWEST: ${{ matrix.prefer_lowest }}
                COMPOSER_PREFER_STABLE: 1

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure platform PHP version for Composer
              run: docker run --rm composer config platform.php ${{ matrix.composer_platform_php }}

            - name: Install Composer dependencies
              run: docker run --rm composer install

            - name: Run PHPUnit
              run: vendor/bin/phpunit
