name: PHPUnit

on:
    - push

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ${{ matrix.image }}
            env:
                COMPOSER_PREFER_STABLE: 1
                COMPOSER_PREFER_LOWEST: ${{ matrix.prefer_lowest }}

        strategy:
            matrix:
                image:
                    - 'php:8.0-cli-alpine'
                    - 'php:8.1-cli-alpine'
                prefer_lowest:
                    - 1
                    - 0

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Composer
              run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

            - name: Install Composer dependencies
              run: composer update --no-interaction --no-progress

            - name: Run PHPUnit
              run: vendor/bin/phpunit
